#
# HTTP Status Codes.
#
#	 HTTP_STATUS_CODE_OK 										= 200
#	 HTTP_STATUS_CODE_ACCEPTED								= 202
#	 HTTP_STATUS_MULTI_STATUS 								= 207
#	 HTTP_STATUS_CODE_CONFLICT								= 409
#	 HTTP_STATUS_CODE_UNPROCESSABLE_ENTITY		= 422
#	 HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR 	= 500
#	 HTTP_STATUS_CODE_BAD_GATEWAY 						= 502
#	 HTTP_STATUS_SERVICE_UNAVAILABLE 					= 503
#	 HTTP_STATUS_GATEWAY_TIMEOUT							= 504
#
# Reason codes representing different (common) business conditions.
#
XC00202I=200,false
XC00203I=202,false
XC00401E=422,false
XC00402E=422,false
XC00403E=422,false
XC00404E=422,false
XC00405E=422,false
XC00406E=422,false
XC00407E=422,false
#
# Reason codes representing Refund / Reversal.
#
XC00431E=422,false
XC00432E=422,false
XC00433E=422,false
XC00434E=422,false
XC00435W=200,false
#
#Reason codes representing Communication Errors.
#
XC00500E=500,true
XC00502E=502,true
XC00503E=503,true
XC00504E=504,true
XC00441I=200,false
XC00442E=409,false
XCMULTIW=207,false
XC00998E-504,true
#
#