secure-envelope-version=compact-v3
secure-envelope-request-name=intimation_request
secure-envelope-response-name=intimation_response
encryption-encoding=base64
payload-encryption-cipher=AES/CBC/PKCS7Padding
payload-encryption-key-alias=acme-aes-192
secretkey-encryption-cipher=RSA/ECB/PKCS1Padding
secretkey-decryption-key-alias=acme-rsa-1024
secretkey-encryption-key-alias=ixc-rsa-1024
namespace-injection=true