# Intimation
BAD_GATEWAY=XC00502E
CLIENT_CODE_VIRTUAL_ACCOUNT_NUMBER_MISMATCH=XC00403E
DUPLICATE_TRANSACTION_ID=XC00404E
GATEWAY_TIMEOUT=XC00504E
INTERNAL_SERVER_ERROR=XC00500E
INVALID_CLIENT_CODE=XC00401E
INVALID_CLIENT_IFSC_CODE=XC00407E
INVALID_SENDER_IFSC_CODE=XC00406E
INVALID_VIRTUAL_ACCOUNT_NUMBER=XC00402E
MISMATCH_CLIENT_ACCOUNT_NUMBER=XC00405E
MULTI_STATUS=XCMULTIW
OK=XC00202I
REQUEST_ACCEPTED=XC00203I
REQUEST_NOT_VALID=XC00101E
RESPONSE_NOT_VALID=XC00102E
RESPONSE_TIMEOUT =XC00998E
RESPONSE_UNPROCESSABLE =XC00999E
SERVICE_UNAVAILABLE=XC00503E
TRANSACTION_ACCEPTED=XC00441I
TRANSACTION_REJECTED=XC00442E
# Refund / Reversal Intimation
REMITTER_ACCOUNT_NUMBER_NOT_FOUND=XC00431E
REVERSAL_STATUS_NOT_FOUND=XC00432E
REVERSAL_STATUS_CODE_NOT_VALID=XC00433E
REFUND_CODE_NOT_FOUND=XC00434E
REJECTION_REASON_NOT_PROVIDED=XC00435W
