#Map the last 3 digits of a transaction ID with a Reason Code.
441=TRANSACTION_ACCEPTED
442=TRANSACTION_REJECTED
500=INTERNAL_SERVER_ERROR
502=BAD_GATEWAY
503=SERVICE_UNAVAILABLE
504=GATEWAY_TIMEOUT
401=INVALID_CLIENT_CODE
402=INVALID_VIRTUAL_ACCOUNT_NUMBER
403=CLIENT_CODE_VIRTUAL_ACCOUNT_NUMBER_MISMATCH
404=DUPLICATE_TRANSACTION_ID
406=INVALID_SENDER_IFSC_CODE
431=REMITTER_ACCOUNT_NUMBER_NOT_FOUND
432=REJECTION_REASON_NOT_PROVIDED
