
package com.icici.xpress_connect.ws.ecollection;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IntimationPort", targetNamespace = "http://www.icicibank.com/ws/intimation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntimationPort {


    /**
     * 
     * @param intimationRequest
     * @return
     *     returns com.icici.xpress_connect.ws.ecollection.IntimationResponseType
     */
    @WebMethod(operationName = "Intimate", action = "http://www.icicibank.com/api/acme/intimation")
    @WebResult(name = "intimation_response", targetNamespace = "http://www.icicibank.com/api/acme", partName = "IntimationResponse")
    public IntimationResponseType intimate(
        @WebParam(name = "intimation_request", targetNamespace = "http://www.icicibank.com/api/acme", partName = "IntimationRequest")
        IntimationRequestType intimationRequest);

    /**
     * 
     * @param refundIntimationRequest
     * @return
     *     returns com.icici.xpress_connect.ws.ecollection.RefundIntimationResponseType
     */
    @WebMethod(operationName = "RefundIntimate", action = "http://www.icicibank.com/api/acme/refund-intimation")
    @WebResult(name = "refund_intimation_response", targetNamespace = "http://www.icicibank.com/api/acme", partName = "RefundIntimationResponse")
    public RefundIntimationResponseType refundIntimate(
        @WebParam(name = "refund_intimation_request", targetNamespace = "http://www.icicibank.com/api/acme", partName = "RefundIntimationRequest")
        RefundIntimationRequestType refundIntimationRequest);

}
