
package com.icici.xpress_connect.ws.ecollection;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IntimationSOAP11WS", targetNamespace = "http://www.icicibank.com/ws/intimation", wsdlLocation = "file:/C:/Workspaces/workspace-sts/ixc-ecollection-profunds-api-v3.6-java-soap-webservice-server-acme/src/main/resources/wsdl/intimation.wsdl")
public class IntimationSOAP11WS
    extends Service
{

    private final static URL INTIMATIONSOAP11WS_WSDL_LOCATION;
    private final static WebServiceException INTIMATIONSOAP11WS_EXCEPTION;
    private final static QName INTIMATIONSOAP11WS_QNAME = new QName("http://www.icicibank.com/ws/intimation", "IntimationSOAP11WS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Workspaces/workspace-sts/ixc-ecollection-profunds-api-v3.6-java-soap-webservice-server-acme/src/main/resources/wsdl/intimation.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTIMATIONSOAP11WS_WSDL_LOCATION = url;
        INTIMATIONSOAP11WS_EXCEPTION = e;
    }

    public IntimationSOAP11WS() {
        super(__getWsdlLocation(), INTIMATIONSOAP11WS_QNAME);
    }

    public IntimationSOAP11WS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IntimationPort
     */
    @WebEndpoint(name = "IntimationSOAP11WS")
    public IntimationPort getIntimationSOAP11WS() {
        return super.getPort(new QName("http://www.icicibank.com/ws/intimation", "IntimationSOAP11WS"), IntimationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntimationPort
     */
    @WebEndpoint(name = "IntimationSOAP11WS")
    public IntimationPort getIntimationSOAP11WS(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.icicibank.com/ws/intimation", "IntimationSOAP11WS"), IntimationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTIMATIONSOAP11WS_EXCEPTION!= null) {
            throw INTIMATIONSOAP11WS_EXCEPTION;
        }
        return INTIMATIONSOAP11WS_WSDL_LOCATION;
    }

}
