api-user-authentication-type=custom-auth
api-user-authentication-parameters-location=soap-header
api-user-authentication-userId-token-name={http://www.icicibank.com/api/acme-ext}:API-UserId-Token
api-user-authentication-access-token-name={http://www.icicibank.com/api/acme-ext}:API-Access-Token