api-user-authentication-type=custom-auth
api-user-authentication-parameters-location=http-header
api-user-authentication-userId-token-name=API-UserId-Token
api-user-authentication-access-token-name=API-Access-Token