encryption-encoding=hex
encryption-keytype=symmetric
encryption-cipher=DESede/CFB/PKCS7Padding
encryption-providerkey-alias=acme-aes-192
encryption-providerkey-length=192
encryption-consumerkey-alias=acme-aes-192
encryption-consumerkey-length=192
encryption-select-fields=transactionId|transactionDatetime|transactionAmount|senderAccountNumber|clientAccountNumber
encryption-iv-fieldname=Cipher-IV
encryption-iv-location=header