encryption-encoding=hex
encryption-keytype=asymmetric
encryption-cipher=RSA/ECB/PKCS1Padding
encryption-providerkey-alias=acme-rsa-1024
encryption-providerkey-length=1024
encryption-consumerkey-alias=ixc-rsa-1024
encryption-consumerkey-length=1024
encryption-select-fields=*